Remove problematic steps
My initial test of the new docs reveals a blocker and a few issues. Since these steps are detailed on the [other page](https://docs.newrelic.com/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-containerized-function-monitoring/enable-containerized-function/), it might be best to just remove these steps to clear up confusion about which steps to follow.

The `Dockerfile` is broken on the second step `Once you're finished, create a new Docker file with the following configuration:`

---

The numbering of sub steps are all 1, 1, 1 and don't increment.

---

This command does not work (on my M3 Mac):

```sh
docker build --platform linux/amd64 -t docker-image:test
```

It errors with:

```sh
$ docker build --platform linux/amd64 -t docker-image:test
ERROR: "docker buildx build" requires exactly 1 argument.
See 'docker buildx build --help'.

Usage:  docker buildx build [OPTIONS] PATH | URL | -

Start a build
```

It should instead use a docker-compose.yml file like:

```yaml
version: '3'

services:
  containerized-lambda:
    build:
      dockerfile: Dockerfile
      platforms:
        - "linux/amd64"
    image: docker-image:test

With command:

```sh
docker compose up
```

Which then errors with:

```sh
$ docker compose up
[+] Running 1/1
 ! containerized-lambda Warning                                                                                                                                                                                                                                                                                   2.0s 
[+] Building 0.0s (1/1) FINISHED                                                                                                                                                                                                                                                                  docker:desktop-linux
 => [containerized-lambda internal] load build definition from Dockerfile                                                                                                                                                                                                                                         0.0s
 => => transferring dockerfile: 256B                                                                                                                                                                                                                                                                              0.0s
failed to solve: dockerfile parse error on line 3: unknown instruction: ${LAMBDA_TASK_ROOT}
```